import './style.css';
import snapshot from './operational-snapshot.json';
import {dateState,selectVoyages,escapeHtml as esc,snapshotCsv} from './operational.js';
const rows=snapshot.voyages,asOf=snapshot.fetchedAt;
const labels={past:'종료시각 경과 · OPR 유지',within:'등록 기간 내',future:'시작시각 도래 전',unknown:'기간 확인 필요'};
const state=v=>dateState(v,asOf),past=rows.filter(v=>state(v)==='past'),vesselCount=new Set(rows.map(v=>v.name)).size;
const stamp=v=>v?new Intl.DateTimeFormat('ko-KR',{timeZone:'UTC',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)):'미확인';
const navs=[['fleet','실제 항차'],['review','상태 검토'],['brief','항차 브리핑'],['connections','데이터 연결']];
let page=navs.some(([p])=>p===location.hash.slice(1))?location.hash.slice(1):'fleet';
let search='',filter='all',sort='name',selected=null,lastFocus=null;
const badge=v=>`<span class="badge ${state(v)==='past'?'warn':'unknown'}">${labels[state(v)]}</span>`;
const portNames=v=>v.ports.map(p=>p.name).join(' → ')||'기항 없음';
const current=()=>selectVoyages(rows,{search,state:filter,asOf}).slice().sort((a,b)=>sort==='end'?(a.end||'').localeCompare(b.end||''):a.name.localeCompare(b.name)||a.voyage.localeCompare(b.voyage));
const notice=()=>`<div class="demo-notice"><span class="notice-dot"></span><strong>실제 Dataloy · 공개 스냅샷</strong><span>${stamp(asOf)} UTC 조회 · 자동 갱신 미연결</span></div>`;
const heading=(title,desc,action='')=>`<div class="page-heading"><div><span class="eyebrow">DATALOY / FLEET OPERATIONS</span><h1>${title}</h1><p>${desc}</p></div>${action}</div>`;
document.querySelector('#app').innerHTML=`<a class="skip" href="#main">본문으로 건너뛰기</a><aside class="sidebar"><a class="brand" href="#fleet">FLEET<span class="brand-sub">OPERATIONS</span></a><div class="workspace"><span class="workspace-icon">D</span><span>Dataloy snapshot<small>실제 항차 · 공개 검토</small></span></div><div class="nav-label">WORKSPACE</div><nav>${navs.map(([p,label],i)=>`<button class="nav-item" data-page="${p}" aria-label="${label}"><b aria-hidden="true">${['▦','✓','▤','↔'][i]}</b><span>${label}</span>${p==='review'?`<span class="nav-count">${past.length}</span>`:''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="side-help">일정의 근거부터.<br>실제 항차를 확인하세요.<span>OPR · 일정 · 상태 검토</span></div></div></aside><div class="shell"><header class="topbar"><button class="icon-button mobile-menu" id="menu" aria-label="메뉴 열기" aria-expanded="false">☰</button><div class="breadcrumb">Workspace <span id="breadcrumb"></span></div><div class="topbar-right"><span class="timezone">등록 일정 UTC</span><span class="demo-pill">DATALOY SNAPSHOT</span></div></header><main id="main" tabindex="-1"></main><footer class="footer"><span>VMwareconnect · Fleet Operations</span><span>실제 항차 스냅샷 · 본선 위치 및 Outlook 미연결</span></footer></div><div id="drawer-root"></div>`;
function fleet(){return heading('실제 항차','Operational 상태의 항차와 등록 일정을 확인하세요.',`<button class="button" id="export">항차 CSV 다운로드</button><button class="button primary" data-page="brief">항차 브리핑</button>`)+notice()+`<section class="metrics" aria-label="실제 항차 요약"><button class="metric" data-filter="all"><div>Operational 항차</div><strong>${rows.length}<small>건</small></strong><p>전체 페이지와 API 총건수 일치</p></button><div class="metric"><div>고유 선박</div><strong>${vesselCount}<small>척</small></strong><p>동일 선박의 복수 항차 포함</p></div><button class="metric" data-filter="within"><div>등록 기간 내 항차</div><strong>${rows.filter(v=>state(v)==='within').length}<small>건</small></strong><p>실제 항해 여부는 미확인</p></button><button class="metric" data-filter="past"><div>종료시각 경과 · OPR 유지</div><strong>${past.length}<small>건</small></strong><p>등록 상태 검토 필요</p></button></section><section class="position-notice"><div><strong>선박 위치 확인 대기</strong><p>현재 데이터는 항차와 기항 일정입니다. 검증된 본선 보고 또는 AIS 위치를 연결하면 지도에 표시합니다.</p></div><span class="badge unknown">위치 추정 안 함</span></section><div class="fleet-tools"><div class="tabs">${[['all','전체 항차'],['within','등록 기간 내'],['past','종료시각 경과']].map(([s,l])=>`<button data-filter="${s}" class="${filter===s?'active':''}">${l}</button>`).join('')}</div></div><section class="fleet-table-panel"><div class="table-toolbar"><div><h2>항차 목록 <span id="result-count"></span></h2><p>종료시각은 목적항 ETA나 실제 완료시각으로 확정하지 않았습니다.</p></div><div class="table-controls"><label class="search"><input id="fleet-search" aria-label="선박, 항차, 기항 검색" placeholder="선박, 항차, 기항 검색" value="${esc(search)}"></label><select id="sort" aria-label="항차 정렬"><option value="name">선박명 순</option><option value="end">종료시각 순</option></select></div></div><div class="table-scroll"><table><thead><tr><th>선박 / 항차</th><th>참조번호</th><th>기항 순서</th><th>등록 시작 UTC</th><th>등록 종료 UTC</th><th>일정 검토</th></tr></thead><tbody id="vessel-rows"></tbody></table></div><div class="table-footer"><span id="result-footer"></span><span>OPR ≠ 현재 항해 중</span></div></section>`;}
function renderRows(){const list=current();document.querySelector('#vessel-rows').innerHTML=list.length?list.map(v=>`<tr><td><button class="vessel-cell" data-voyage="${v.id}"><span><strong>${esc(v.name)}</strong><small>${esc(v.voyage)} · OPR</small></span></button></td><td>${esc(v.reference)}</td><td class="route-cell">${esc(portNames(v))}</td><td>${stamp(v.start)}</td><td>${stamp(v.end)}</td><td>${badge(v)}</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty-state"><strong>검색 결과가 없습니다</strong><button class="button" id="clear">필터 초기화</button></div></td></tr>';document.querySelector('#result-count').textContent=list.length;document.querySelector('#result-footer').textContent=`전체 ${rows.length}건 중 ${list.length}건`;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));}
function review(){return heading('상태 검토','등록 종료시각이 지났는데 Operational로 남아 있는 항차입니다.')+notice()+`<p class="review-explanation">총 ${past.length}건. 본선 보고와 대조하기 전에는 실제 완료·지연·데이터 오류로 확정할 수 없습니다. 검토 기준은 스냅샷 조회시각입니다.</p><div class="review-grid">${past.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(v=>`<article class="review-card">${badge(v)}<h2 class="review-name">${esc(v.name)}</h2><p>항차 ${esc(v.voyage)} · 참조 ${esc(v.reference)}<br>등록 종료: ${stamp(v.end)} UTC<br>Dataloy 상태: OPR</p><button class="button" data-voyage="${v.id}">항차 상세 확인 →</button></article>`).join('')}</div>`;}
function briefing(){return heading('항차 브리핑','조회 시점의 실제 Dataloy 항차를 정리했습니다.',`<button class="button primary" id="brief-download">브리핑 다운로드</button>`)+notice()+`<article class="brief-paper"><span class="eyebrow">${stamp(asOf)} UTC</span><h2>선박 ${vesselCount}척, 항차 ${rows.length}건.</h2><p class="brief-lead">등록 기간 내 항차 ${rows.filter(v=>state(v)==='within').length}건.<br>종료시각 경과 후 OPR 유지 ${past.length}건.</p><div class="brief-note">자동 동기화가 아닌 조회 시점 스냅샷입니다. Outlook 미연결로 Noon / Port / Working report 대조 결과와 실제 위치는 아직 없습니다.</div><h3><span>선박별 항차</span></h3><div class="brief-vessels">${rows.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(v=>`<button data-voyage="${v.id}"><strong>${esc(v.name)}</strong><span>${esc(v.voyage)}</span>${badge(v)}</button>`).join('')}</div></article>`;}
function connections(){return heading('데이터 연결','연결 검증과 공개 사이트의 갱신 상태를 구분해 표시합니다.')+notice()+`<div class="connection-grid"><article class="connection-card"><span class="connection-label">DATALOY</span><h2>실제 항차 수집 완료</h2><span class="badge ok">OAuth · 읽기 검증 성공</span><p>${rows.length}건을 전체 페이지에서 가져왔습니다. 공개 사이트에는 승인된 선박명·항차번호·기항·등록 일정만 포함됩니다.</p><ul><li>조회: ${stamp(asOf)} UTC</li><li>사이트 자동 동기화: 미연결</li><li>API 키와 토큰: 브라우저에 없음</li></ul></article><article class="connection-card"><span class="connection-label">OUTLOOK</span><h2>본선 보고 수집 대기</h2><span class="badge unknown">자동 수집 미연결</span><p>VMware Horizon의 Outlook 화면 접근을 확인했습니다. Noon report, Port report, Working report의 자동 수집·원문 근거·Dataloy 대조는 남아 있습니다.</p></article><article class="connection-card"><span class="connection-label">POSITION</span><h2>실제 위치 미확인</h2><span class="badge unknown">지도 위치 데이터 대기</span><p>기항지를 선박의 현재 위치로 사용하지 않습니다. 기준시각과 출처가 검증된 보고 위치를 확보하면 지도 표시를 연결합니다.</p></article></div>`;}
function render(){document.querySelector('#main').innerHTML=page==='fleet'?fleet():page==='review'?review():page==='brief'?briefing():connections();document.querySelector('#breadcrumb').textContent=navs.find(n=>n[0]===page)[1];document.querySelectorAll('.nav-item').forEach(b=>{b.classList.toggle('active',b.dataset.page===page);b.setAttribute('aria-current',b.dataset.page===page?'page':'false');});document.querySelector('.sidebar').classList.remove('open');document.querySelector('#menu').setAttribute('aria-expanded','false');if(page==='fleet'){renderRows();document.querySelector('#sort').value=sort;}}
function navigate(p){if(!navs.some(n=>n[0]===p))return;close();page=p;location.hash=p;render();window.scrollTo(0,0);}
function open(id){selected=rows.find(v=>v.id===id);if(!selected)return;lastFocus=document.activeElement;const v=selected;document.querySelector('#drawer-root').innerHTML=`<div class="drawer-backdrop" id="backdrop"></div><section class="drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title"><div class="drawer-top"><span class="eyebrow">DATALOY VOYAGE</span><button class="icon-button" id="close" aria-label="항차 상세 닫기">✕</button></div><div class="drawer-title"><div><h2 id="drawer-title">${esc(v.name)}</h2><p>항차 ${esc(v.voyage)} · 참조 ${esc(v.reference)} <span class="opr">OPR</span></p></div></div><div class="drawer-content">${badge(v)}<div class="detail-grid"><div><small>등록 시작 UTC</small><strong>${stamp(v.start)}</strong><span>voyageStartDateGMT</span></div><div><small>등록 종료 UTC</small><strong>${stamp(v.end)}</strong><span>voyageEndDateGMT</span></div><div><small>본선 위치</small><strong>미확인</strong><span>검증된 위치 보고 미연결</span></div><div><small>보고 대조</small><strong>미수행</strong><span>Outlook 자동 수집 미연결</span></div></div><h3 class="ports-heading">Dataloy 등록 기항 순서</h3><ol class="port-sequence">${v.ports.map(p=>`<li><span>${esc(p.name)}</span><small>등록 순번 ${esc(p.sequence??'미확인')}</small></li>`).join('')}</ol><p class="subtle-note">기항 순서는 등록 일정이며 현재 위치나 실제 방문 완료를 뜻하지 않습니다. 본선 ETA와 계획·실적 대조는 후속 검증 대상입니다.</p></div><div class="drawer-footer"><span>실제 스냅샷 · ${stamp(asOf)} UTC</span></div></section>`;document.body.classList.add('drawer-open');document.querySelector('.shell').inert=true;document.querySelector('.sidebar').inert=true;document.querySelector('#close').focus();}
function close(){document.querySelector('#drawer-root').innerHTML='';document.body.classList.remove('drawer-open');document.querySelector('.shell').inert=false;document.querySelector('.sidebar').inert=false;selected=null;lastFocus?.focus();}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
document.addEventListener('click',e=>{if(e.target.id==='backdrop')return close();const b=e.target.closest('button');if(!b)return;if(b.dataset.page)return navigate(b.dataset.page);if(b.dataset.voyage)return open(b.dataset.voyage);if(b.dataset.filter){filter=b.dataset.filter;renderRows();return;}if(b.id==='menu'){const shown=document.querySelector('.sidebar').classList.toggle('open');b.setAttribute('aria-expanded',String(shown));}if(b.id==='close')close();if(b.id==='clear'){search='';filter='all';document.querySelector('#fleet-search').value='';renderRows();}if(b.id==='export')download('dataloy-operational-snapshot.csv',snapshotCsv(current(),asOf),'text/csv;charset=utf-8');if(b.id==='brief-download')download('dataloy-voyage-brief.txt',`Dataloy snapshot ${asOf}\n${vesselCount}척 / ${rows.length}항차 / 종료시각 경과 ${past.length}건\n자동 갱신·Outlook 대조 미연결\n\n`+rows.map(v=>`${v.name} | ${v.voyage} | ${portNames(v)} | 등록 종료 ${v.end} | ${labels[state(v)]}`).join('\n'),'text/plain;charset=utf-8');});
document.addEventListener('input',e=>{if(e.target.id==='fleet-search'){search=e.target.value;renderRows();}});
document.addEventListener('change',e=>{if(e.target.id==='sort'){sort=e.target.value;renderRows();}});
document.addEventListener('keydown',e=>{if(selected&&e.key==='Escape')close();if(selected&&e.key==='Tab'){e.preventDefault();document.querySelector('#close').focus();}});
window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(p==='main'){document.querySelector('#main').focus();return;}if(navs.some(n=>n[0]===p)&&page!==p){close();page=p;render();}});
render();
