import './fleet.css';
import snapshot from './operational-snapshot.json';
import {dateState,selectVoyages,sortVoyages,partyOptions,laycan,laycanLabel,laycanStatus,registeredCount,rotationContext,portCallState,callDateLabel,money,amountLabel,SORTS,escapeHtml as esc,snapshotCsv} from './operational.js';
const rows=snapshot.voyages,asOf=snapshot.fetchedAt;
const labels={past:'End date passed',within:'Within schedule',future:'Not started',unknown:'Dates unavailable'};
const state=v=>dateState(v,asOf),past=rows.filter(v=>state(v)==='past'),vesselCount=new Set(rows.map(v=>v.name)).size;
const stamp=v=>v?new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',year:'numeric',month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)):'Not verified';
const navs=[['fleet','Voyages'],['review','Review queue'],['brief','Voyage briefing'],['connections','Connections']];
let page=navs.some(([p])=>p===location.hash.slice(1))?location.hash.slice(1):'fleet';
let search='',filter='all',party='all',sort='name',selected=null,lastFocus=null;
// Fields that arrive only once collection is extended. Absent data draws no control at all.
const parties=partyOptions(rows),hasParty=parties.length>0,hasCargo=rows.some(v=>v.commercial?.cargo),hasCall=rows.some(v=>v.ports.some(p=>p.arrival||p.departure));
const sorts=SORTS.filter(([k])=>k!=='party'||hasParty);
const badge=v=>`<span class="badge ${state(v)==='past'?'warn':'unknown'}">${labels[state(v)]}</span>`;
const portNames=v=>v.ports.map(p=>p.name).join(' → ')||'No port calls';
const current=()=>sortVoyages(selectVoyages(rows,{search,state:filter,party,asOf}),sort);
const icons={ship:'M3 13l9-4 9 4-3 7H6l-3-7z M8 10V4h8v6 M12 4V1',fleet:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',review:'M9 12l2 2 4-4 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',brief:'M6 3h9l3 3v15H6z M9 10h6 M9 14h6 M9 18h4',connections:'M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2 M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',arrow:'M4 12h16 M15 7l5 5-5 5',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',menu:'M3 6h18 M3 12h18 M3 18h18',close:'M5 5l14 14 M19 5L5 19'};
const icon=name=>`<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]}"/></svg>`;
const dateCell=value=>value?`<span class="date-cell">${new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',year:'numeric'}).format(new Date(value))}<small>${new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value))} UTC</small></span>`:'Not verified';
const callDates=p=>[callDateLabel(p.arrival,p.arrivalFixed,'arrival'),callDateLabel(p.departure,p.departureFixed,'departure')].filter(Boolean);
const routeCell=v=>{
 if(!v.ports.length)return 'No port calls';
 const route=rotationContext(v.ports);
 return (route.completed?'<span class="badge ok rotation-completed">Rotation completed</span>':'')+
 '<ol class="route-context" aria-label="Port call progress">'+route.calls.map(({port:p,state,label})=>
 '<li class="'+state+'"><span class="route-marker"></span><div><small>'+label+'</small><strong>'+esc(p.name)+'</strong><em>'+esc(p.purpose)+'</em>'+callDates(p).map(date=>'<span class="route-date">'+esc(date)+'</span>').join('')+'</div></li>').join('')+
 '</ol><small class="route-note">'+v.ports.length+' calls total · Full rotation in voyage details</small>';
};
const notice=()=>`<div class="demo-notice"><span class="notice-dot"></span><strong>Dataloy snapshot</strong><span>${stamp(asOf)} UTC · Manual snapshot</span></div>`;
const heading=(title,desc,action='')=>`<div class="page-heading"><div><span class="eyebrow">DATALOY / FLEET OPERATIONS</span><h1>${title}</h1><p>${desc}</p></div>${action}</div>`;
document.querySelector('#app').innerHTML=`<a class="skip" href="#main">Skip to content</a><aside class="sidebar"><a class="brand" href="#fleet"><span class="brand-symbol">${icon('ship')}</span><span>Fleet<span class="brand-sub">OPERATIONS</span></span></a><div class="workspace"><span class="workspace-icon">D</span><span>Dataloy snapshot<small>Voyage review workspace</small></span></div><div class="nav-label">WORKSPACE</div><nav>${navs.map(([p,label],i)=>`<button class="nav-item" data-page="${p}" aria-label="${label}">${icon(p)}<span>${label}</span>${p==='review'?`<span class="nav-count">${past.length}</span>`:''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="side-help">Your fleet.<br>A clearer perspective.<span>SCHEDULES / OPERATIONS / REVIEW</span></div></div></aside><div class="shell"><header class="topbar"><button class="icon-button mobile-menu" id="menu" aria-label="Toggle navigation" aria-expanded="false">${icon('menu')}</button><div class="breadcrumb">Workspace <span id="breadcrumb"></span></div><div class="topbar-right"><span class="timezone">Voyage dates UTC · Port times LT</span><span class="demo-pill">DATALOY SNAPSHOT</span></div></header><main id="main" tabindex="-1"></main><footer class="footer"><span>VMwareconnect · Fleet Operations</span><span>Dataloy snapshot · Position & Outlook not connected</span></footer></div><div id="drawer-root"></div>`;
const ladenText=c=>c?.laden===true?'Laden':c?.laden===false?'Ballast':'Not determined';
const invoiceNote=i=>i?.statuses?.length?i.statuses.map(t=>`${esc(t.label||t.code)} ${esc(registeredCount(t.count))}`).join(' \u00b7 '):'No status breakdown collected';
const invoiceTotal=i=>{const t=money(i?.total,i?.currency);return i?`${registeredCount(i.count)}${t?` \u00b7 ${t}`:''}`:'Not collected';};
const laytimeText=l=>{if(!l)return 'Not collected';if(l.registered!==true)return l.registered===false?'Not registered':'Not determined';const side={demurrage:'Demurrage',despatch:'Despatch',none:'No claim'}[l.outcome]||'Registered',amount=money(l.amount,l.currency);return amount?`${side} \u00b7 ${amount}`:side;};
const commercialBlock=v=>{const c=v.commercial;if(!c)return '';const l=laycan(v);return `<h3 class="ports-heading">Voyage commercials</h3><div class="detail-grid"><div><small>Cargo</small><strong>${c.cargo?`${registeredCount(c.cargo.count)} \u00b7 ${ladenText(c.cargo)}`:'Not collected'}</strong><span>${c.cargo?.description?esc(c.cargo.description):'No cargo description collected'}</span></div><div><small>Cargo laycan</small><strong>${esc(laycanStatus(v))}</strong><span>Window registered against the cargo</span></div><div><small>Freight</small><strong>${esc(amountLabel(c.freight))}</strong><span>As registered on the voyage, not an invoiced total</span></div><div><small>Port costs</small><strong>${esc(amountLabel(c.portCosts))}</strong><span>${c.portCosts?.count!=null?`Across ${esc(c.portCosts.count)} port call entries`:'Registered port expenses'}</span></div><div><small>Invoices</small><strong>${esc(invoiceTotal(c.invoices))}</strong><span>${invoiceNote(c.invoices)}</span></div><div><small>Laytime</small><strong>${esc(laytimeText(c.laytime))}</strong><span>\u201cNot registered\u201d does not mean there is no claim</span></div></div>`;};
function fleet(){return heading('Voyages','A clear view of your operational voyages and registered schedules.',`<button class="button" id="export">${icon('download')}Export CSV</button><button class="button primary" data-page="brief">Voyage briefing</button>`)+notice()+`<section class="metrics" aria-label="Voyage overview"><button class="metric" data-filter="all"><div>Operational voyages</div><strong>${rows.length}<small></small></strong><p>Complete snapshot · all pages verified</p></button><div class="metric"><div>Vessels</div><strong>${vesselCount}<small></small></strong><p>Distinct vessels across all voyages</p></div><button class="metric" data-filter="within"><div>Within schedule</div><strong>${rows.filter(v=>state(v)==='within').length}<small></small></strong><p>Based on registered dates</p></button><button class="metric" data-filter="past"><div>End date passed</div><strong>${past.length}<small></small></strong><p>Review registered OPR status</p></button></section><section class="position-notice"><div><strong>Vessel positions are not connected yet</strong><p>This workspace shows voyage schedules. Verified vessel reports or AIS data will enable the position map.</p></div><span class="badge unknown">Position unavailable</span></section><div class="fleet-tools"><div class="tabs">${[['all','All voyages'],['within','Within schedule'],['past','End date passed']].map(([s,l])=>`<button data-filter="${s}" class="${filter===s?'active':''}">${l}</button>`).join('')}</div></div><section class="fleet-table-panel"><div class="table-toolbar"><div><h2>Voyages <span id="result-count"></span></h2><p>Registered end dates are not verified arrival times or completion records.</p></div><div class="table-controls"><label class="search">${icon('search')}<input id="fleet-search" aria-label="Search vessel, voyage or port" placeholder="Search vessel, voyage or port" value="${esc(search)}"></label>${hasParty?`<select id="party" aria-label="Filter by charterer or operator"><option value="all">All charterers / operators</option>${parties.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('')}</select>`:''}<select id="sort" aria-label="Sort voyages">${sorts.map(([k,l])=>`<option value="${k}">${l}</option>`).join('')}</select></div></div><div class="table-scroll"><table><thead><tr><th>Vessel / voyage</th><th>Reference</th><th>Port rotation${hasCall?' · LT':''}</th><th>Registered start · UTC</th><th>Registered end · UTC</th><th>Schedule review</th></tr></thead><tbody id="vessel-rows"></tbody></table></div><div class="table-footer"><span id="result-footer"></span><span>OPR is a workflow status, not a sailing status</span></div></section>`;}
function renderRows(){const list=current();document.querySelector('#vessel-rows').innerHTML=list.length?list.map(v=>`<tr><td><button class="vessel-cell" data-voyage="${v.id}"><span class="vessel-avatar">${icon('ship')}</span><span><strong>${esc(v.name)}</strong><small>${esc(v.voyage)} · OPR</small>${hasCargo?`<small class="laycan-line"><b>LAYCAN</b>${esc(laycanStatus(v))}</small>`:''}</span></button></td><td><a class="reference-link" href="https://safeeninvictus.dataloy.com/#/voyages/voyage-drawer/${encodeURIComponent(v.dataloyId)}" target="_blank" rel="noopener noreferrer" aria-label="Open ${esc(v.reference)} in Dataloy VMS">${esc(v.reference)}${icon('arrow')}</a></td><td class="route-cell">${routeCell(v)}</td><td>${dateCell(v.start)}</td><td>${dateCell(v.end)}</td><td>${badge(v)}</td></tr>`).join(''):`<tr><td colspan="6"><div class="empty-state"><strong>No voyages found</strong><button class="button" id="clear">Clear filters</button></div></td></tr>`;document.querySelector('#result-count').textContent=list.length;document.querySelector('#result-footer').textContent=`Showing ${list.length} of ${rows.length} voyages`;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));}
function review(){return heading('Review queue','Voyages that remain Operational after their registered end date.')+notice()+`<p class="review-explanation">${past.length} voyages need a status review. These are not confirmed delays or completed voyages. Compare vessel reports before drawing conclusions. All checks use the snapshot time.</p><div class="review-grid">${past.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(v=>`<article class="review-card">${badge(v)}<h2 class="review-name">${esc(v.name)}</h2><p>Voyage ${esc(v.voyage)} · Ref ${esc(v.reference)}<br>Registered end: ${stamp(v.end)} UTC<br>Dataloy status: OPR</p><button class="button" data-voyage="${v.id}">View voyage →</button></article>`).join('')}</div>`;}
function briefing(){return heading('Voyage briefing','Your operational fleet at the time of the latest snapshot.',`<button class="button primary" id="brief-download">Download briefing</button>`)+notice()+`<article class="brief-paper"><span class="eyebrow">${stamp(asOf)} UTC</span><h2>${vesselCount} vessels. ${rows.length} voyages.</h2><p class="brief-lead">${rows.filter(v=>state(v)==='within').length} voyages within their registered schedule.<br>${past.length} voyages remain OPR after their registered end date.</p><div class="brief-note">This is a fixed snapshot, not a live feed. Noon, port and working reports have not been reconciled. Vessel positions remain unverified.</div><h3><span>Voyages by vessel</span></h3><div class="brief-vessels">${rows.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(v=>`<button data-voyage="${v.id}"><strong>${esc(v.name)}</strong><span>${esc(v.voyage)}</span>${badge(v)}</button>`).join('')}</div></article>`;}
function connections(){return heading('Connections','Understand where your data comes from and what is available.')+notice()+`<div class="connection-grid"><article class="connection-card"><span class="connection-label">DATALOY</span><h2>Voyage snapshot available</h2><span class="badge ok">Read access verified</span><p>All ${rows.length} voyages were retrieved. This workspace publishes approved vessel names, voyage references, port rotations and registered schedules.</p><ul><li>Snapshot: ${stamp(asOf)} UTC</li><li>Automatic refresh: not connected</li><li>Credentials stay outside the browser</li></ul></article><article class="connection-card"><span class="connection-label">OUTLOOK</span><h2>Vessel reports pending</h2><span class="badge unknown">Not connected</span><p>Outlook screen access through VMware Horizon has been verified. Automated noon, port and working report collection and reconciliation are still pending.</p></article><article class="connection-card"><span class="connection-label">POSITION</span><h2>Positions pending</h2><span class="badge unknown">Awaiting verified positions</span><p>Port calls are scheduled destinations, not current vessel positions. The map will use position reports with a verified source and timestamp.</p></article></div>`;}
function render(){document.querySelector('#main').innerHTML=page==='fleet'?fleet():page==='review'?review():page==='brief'?briefing():connections();document.querySelector('#breadcrumb').textContent=navs.find(n=>n[0]===page)[1];document.querySelectorAll('.nav-item').forEach(b=>{b.classList.toggle('active',b.dataset.page===page);b.setAttribute('aria-current',b.dataset.page===page?'page':'false');});document.querySelector('.sidebar').classList.remove('open');document.querySelector('#menu').setAttribute('aria-expanded','false');if(page==='fleet'){renderRows();document.querySelector('#sort').value=sort;const p=document.querySelector('#party');if(p)p.value=party;}}
function navigate(p){if(!navs.some(n=>n[0]===p))return;close();page=p;location.hash=p;render();window.scrollTo(0,0);}
function open(id){selected=rows.find(v=>v.id===id);if(!selected)return;lastFocus=document.activeElement;const v=selected;document.querySelector('#drawer-root').innerHTML=`<div class="drawer-backdrop" id="backdrop"></div><section class="drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title"><div class="drawer-top"><span class="eyebrow">DATALOY VOYAGE</span><button class="icon-button" id="close" aria-label="Close voyage details">${icon('close')}</button></div><div class="drawer-title"><div><h2 id="drawer-title">${esc(v.name)}</h2><p>Voyage ${esc(v.voyage)} · <a class="drawer-reference" href="https://safeeninvictus.dataloy.com/#/voyages/voyage-drawer/${encodeURIComponent(v.dataloyId)}" target="_blank" rel="noopener noreferrer">${esc(v.reference)} ${icon('arrow')}</a> <span class="opr">OPR</span></p></div></div><div class="drawer-content">${badge(v)}<div class="detail-grid"><div><small>Registered start · UTC</small><strong>${stamp(v.start)}</strong><span>Dataloy registered schedule</span></div><div><small>Registered end · UTC</small><strong>${stamp(v.end)}</strong><span>Not a verified completion time</span></div>${hasParty?`<div><small>Responsible operator</small><strong>${v.operator?esc(v.operator):'Not collected'}</strong><span>Operator registered on the voyage</span></div><div><small>Charterer</small><strong>${v.charterer?esc(v.charterer):'Not collected'}</strong><span>Counterparty registered on the voyage</span></div>`:''}<div><small>Vessel position</small><strong>Not verified</strong><span>No verified position feed</span></div><div><small>Report reconciliation</small><strong>Not performed</strong><span>Outlook collection not connected</span></div></div>${commercialBlock(v)}<h3 class="ports-heading">Registered port rotation</h3>${rotationContext(v.ports).completed?'<span class="badge ok rotation-completed">Rotation completed</span>':''}<ol class="port-sequence">${v.ports.map(p=>`<li class="${portCallState(p)}"><span>${esc(p.name)}</span><small>${esc(p.purpose)} · ${{complete:'Completed call',current:'Arrival recorded',scheduled:'Scheduled'}[portCallState(p)]}</small>${p.arrival||p.departure?`<small class="call-dates">${callDates(p).map(esc).join('<br>')}</small>`:''}</li>`).join('')}</ol><p class="subtle-note">“Current schedule” means the first port call without a fixed departure in Dataloy. It does not claim the vessel is physically at that port. Planned dates are unfixed Dataloy schedules, including required arrival times. ATA/ATD are recorded actuals in Dataloy. Port times use LT (local time); explicit-offset timestamps use UTC. Position confirmation and Outlook report reconciliation are pending.</p></div><div class="drawer-footer"><span>Snapshot · ${stamp(asOf)} UTC</span></div></section>`;document.body.classList.add('drawer-open');document.querySelector('.shell').inert=true;document.querySelector('.sidebar').inert=true;document.querySelector('#close').focus();}
function close(){document.querySelector('#drawer-root').innerHTML='';document.body.classList.remove('drawer-open');document.querySelector('.shell').inert=false;document.querySelector('.sidebar').inert=false;selected=null;lastFocus?.focus();}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
document.addEventListener('click',e=>{if(e.target.id==='backdrop')return close();const b=e.target.closest('button');if(!b)return;if(b.dataset.page)return navigate(b.dataset.page);if(b.dataset.voyage)return open(b.dataset.voyage);if(b.dataset.filter){filter=b.dataset.filter;renderRows();return;}if(b.id==='menu'){const shown=document.querySelector('.sidebar').classList.toggle('open');b.setAttribute('aria-expanded',String(shown));}if(b.id==='close')close();if(b.id==='clear'){search='';filter='all';party='all';document.querySelector('#fleet-search').value='';const p=document.querySelector('#party');if(p)p.value='all';renderRows();}if(b.id==='export')download('dataloy-operational-snapshot.csv',snapshotCsv(current(),asOf),'text/csv;charset=utf-8');if(b.id==='brief-download')download('dataloy-voyage-brief.txt',`Dataloy snapshot ${asOf}\n${vesselCount} vessels / ${rows.length} voyages / ${past.length} end dates passed\nAutomatic refresh and Outlook reconciliation not connected\n\n`+rows.map(v=>`${v.name} | ${v.voyage} | ${portNames(v)} | Registered end ${v.end} | ${labels[state(v)]}`).join('\n'),'text/plain;charset=utf-8');});
document.addEventListener('input',e=>{if(e.target.id==='fleet-search'){search=e.target.value;renderRows();}});
document.addEventListener('change',e=>{if(e.target.id==='sort'){sort=e.target.value;renderRows();}if(e.target.id==='party'){party=e.target.value;renderRows();}});
document.addEventListener('keydown',e=>{if(selected&&e.key==='Escape')close();if(selected&&e.key==='Tab'){const items=[...document.querySelectorAll('.drawer a[href],.drawer button:not([disabled]),.drawer [tabindex="0"]')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}} });
window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(p==='main'){document.querySelector('#main').focus();return;}if(navs.some(n=>n[0]===p)&&page!==p){close();page=p;render();}});
render();
