import './fleet.css';
import snapshot from './operational-snapshot.json';
import {dateState,selectVoyages,escapeHtml as esc,snapshotCsv} from './operational.js';
const rows=snapshot.voyages,asOf=snapshot.fetchedAt;
const labels={past:'End date passed',within:'Within schedule',future:'Not started',unknown:'Dates unavailable'};
const state=v=>dateState(v,asOf),past=rows.filter(v=>state(v)==='past'),vesselCount=new Set(rows.map(v=>v.name)).size;
const stamp=v=>v?new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',year:'numeric',month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)):'Not verified';
const navs=[['fleet','Voyages'],['review','Review queue'],['brief','Voyage briefing'],['connections','Connections']];
let page=navs.some(([p])=>p===location.hash.slice(1))?location.hash.slice(1):'fleet';
let search='',filter='all',sort='name',selected=null,lastFocus=null;
const badge=v=>`<span class="badge ${state(v)==='past'?'warn':'unknown'}">${labels[state(v)]}</span>`;
const portNames=v=>v.ports.map(p=>p.name).join(' → ')||'No port calls';
const current=()=>selectVoyages(rows,{search,state:filter,asOf}).slice().sort((a,b)=>sort==='end'?(a.end||'').localeCompare(b.end||''):a.name.localeCompare(b.name)||a.voyage.localeCompare(b.voyage,undefined,{numeric:true}));
const icons={ship:'M3 13l9-4 9 4-3 7H6l-3-7z M8 10V4h8v6 M12 4V1',fleet:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',review:'M9 12l2 2 4-4 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',brief:'M6 3h9l3 3v15H6z M9 10h6 M9 14h6 M9 18h4',connections:'M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2 M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',arrow:'M4 12h16 M15 7l5 5-5 5',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',menu:'M3 6h18 M3 12h18 M3 18h18',close:'M5 5l14 14 M19 5L5 19'};
const icon=name=>`<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]}"/></svg>`;
const dateCell=value=>value?`<span class="date-cell">${new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',year:'numeric'}).format(new Date(value))}<small>${new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value))} UTC</small></span>`:'Not verified';
const routeCell=v=>v.ports.length?`<div class="route-summary" title="${esc(portNames(v))}"><span>${esc(v.ports[0].name)}</span>${v.ports.length>1?icon('arrow')+'<span>'+esc(v.ports.at(-1).name)+'</span>':''}</div><small class="route-note">${v.ports.length} port calls · Full rotation in voyage details</small>`:'No port calls';
const notice=()=>`<div class="demo-notice"><span class="notice-dot"></span><strong>Dataloy snapshot</strong><span>${stamp(asOf)} UTC · Manual snapshot</span></div>`;
const heading=(title,desc,action='')=>`<div class="page-heading"><div><span class="eyebrow">DATALOY / FLEET OPERATIONS</span><h1>${title}</h1><p>${desc}</p></div>${action}</div>`;
document.querySelector('#app').innerHTML=`<a class="skip" href="#main">Skip to content</a><aside class="sidebar"><a class="brand" href="#fleet"><span class="brand-symbol">${icon('ship')}</span><span>Fleet<span class="brand-sub">OPERATIONS</span></span></a><div class="workspace"><span class="workspace-icon">D</span><span>Dataloy snapshot<small>Voyage review workspace</small></span></div><div class="nav-label">WORKSPACE</div><nav>${navs.map(([p,label],i)=>`<button class="nav-item" data-page="${p}" aria-label="${label}">${icon(p)}<span>${label}</span>${p==='review'?`<span class="nav-count">${past.length}</span>`:''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="side-help">Your fleet.<br>A clearer perspective.<span>SCHEDULES / OPERATIONS / REVIEW</span></div></div></aside><div class="shell"><header class="topbar"><button class="icon-button mobile-menu" id="menu" aria-label="Toggle navigation" aria-expanded="false">${icon('menu')}</button><div class="breadcrumb">Workspace <span id="breadcrumb"></span></div><div class="topbar-right"><span class="timezone">All schedules in UTC</span><span class="demo-pill">DATALOY SNAPSHOT</span></div></header><main id="main" tabindex="-1"></main><footer class="footer"><span>VMwareconnect · Fleet Operations</span><span>Dataloy snapshot · Position & Outlook not connected</span></footer></div><div id="drawer-root"></div>`;
function fleet(){return heading('Voyages','A clear view of your operational voyages and registered schedules.',`<button class="button" id="export">${icon('download')}Export CSV</button><button class="button primary" data-page="brief">Voyage briefing</button>`)+notice()+`<section class="metrics" aria-label="Voyage overview"><button class="metric" data-filter="all"><div>Operational voyages</div><strong>${rows.length}<small></small></strong><p>Complete snapshot · all pages verified</p></button><div class="metric"><div>Vessels</div><strong>${vesselCount}<small></small></strong><p>Distinct vessels across all voyages</p></div><button class="metric" data-filter="within"><div>Within schedule</div><strong>${rows.filter(v=>state(v)==='within').length}<small></small></strong><p>Based on registered dates</p></button><button class="metric" data-filter="past"><div>End date passed</div><strong>${past.length}<small></small></strong><p>Review registered OPR status</p></button></section><section class="position-notice"><div><strong>Vessel positions are not connected yet</strong><p>This workspace shows voyage schedules. Verified vessel reports or AIS data will enable the position map.</p></div><span class="badge unknown">Position unavailable</span></section><div class="fleet-tools"><div class="tabs">${[['all','All voyages'],['within','Within schedule'],['past','End date passed']].map(([s,l])=>`<button data-filter="${s}" class="${filter===s?'active':''}">${l}</button>`).join('')}</div></div><section class="fleet-table-panel"><div class="table-toolbar"><div><h2>Voyage register <span id="result-count"></span></h2><p>Registered end dates are not verified arrival times or completion records.</p></div><div class="table-controls"><label class="search">${icon('search')}<input id="fleet-search" aria-label="Search vessel, voyage or port" placeholder="Search vessel, voyage or port" value="${esc(search)}"></label><select id="sort" aria-label="Sort voyages"><option value="name">Vessel name</option><option value="end">End date</option></select></div></div><div class="table-scroll"><table><thead><tr><th>Vessel / voyage</th><th>Reference</th><th>Port rotation</th><th>Registered start · UTC</th><th>Registered end · UTC</th><th>Schedule review</th></tr></thead><tbody id="vessel-rows"></tbody></table></div><div class="table-footer"><span id="result-footer"></span><span>OPR is a workflow status, not a sailing status</span></div></section>`;}
function renderRows(){const list=current();document.querySelector('#vessel-rows').innerHTML=list.length?list.map(v=>`<tr><td><button class="vessel-cell" data-voyage="${v.id}"><span class="vessel-avatar">${icon('ship')}</span><span><strong>${esc(v.name)}</strong><small>${esc(v.voyage)} · OPR</small></span></button></td><td>${esc(v.reference)}</td><td class="route-cell">${routeCell(v)}</td><td>${dateCell(v.start)}</td><td>${dateCell(v.end)}</td><td>${badge(v)}</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty-state"><strong>No voyages found</strong><button class="button" id="clear">Clear filters</button></div></td></tr>';document.querySelector('#result-count').textContent=list.length;document.querySelector('#result-footer').textContent=`Showing ${list.length} of ${rows.length} voyages`;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));}
function review(){return heading('Review queue','Voyages that remain Operational after their registered end date.')+notice()+`<p class="review-explanation">${past.length} voyages need a status review. These are not confirmed delays or completed voyages. Compare vessel reports before drawing conclusions. All checks use the snapshot time.</p><div class="review-grid">${past.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(v=>`<article class="review-card">${badge(v)}<h2 class="review-name">${esc(v.name)}</h2><p>Voyage ${esc(v.voyage)} · Ref ${esc(v.reference)}<br>Registered end: ${stamp(v.end)} UTC<br>Dataloy status: OPR</p><button class="button" data-voyage="${v.id}">View voyage →</button></article>`).join('')}</div>`;}
function briefing(){return heading('Voyage briefing','Your operational fleet at the time of the latest snapshot.',`<button class="button primary" id="brief-download">Download briefing</button>`)+notice()+`<article class="brief-paper"><span class="eyebrow">${stamp(asOf)} UTC</span><h2>${vesselCount} vessels. ${rows.length} voyages.</h2><p class="brief-lead">${rows.filter(v=>state(v)==='within').length} voyages within their registered schedule.<br>${past.length} voyages remain OPR after their registered end date.</p><div class="brief-note">This is a fixed snapshot, not a live feed. Noon, port and working reports have not been reconciled. Vessel positions remain unverified.</div><h3><span>Voyages by vessel</span></h3><div class="brief-vessels">${rows.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(v=>`<button data-voyage="${v.id}"><strong>${esc(v.name)}</strong><span>${esc(v.voyage)}</span>${badge(v)}</button>`).join('')}</div></article>`;}
function connections(){return heading('Connections','Understand where your data comes from and what is available.')+notice()+`<div class="connection-grid"><article class="connection-card"><span class="connection-label">DATALOY</span><h2>Voyage snapshot available</h2><span class="badge ok">Read access verified</span><p>All ${rows.length} voyages were retrieved. This workspace publishes approved vessel names, voyage references, port rotations and registered schedules.</p><ul><li>Snapshot: ${stamp(asOf)} UTC</li><li>Automatic refresh: not connected</li><li>Credentials stay outside the browser</li></ul></article><article class="connection-card"><span class="connection-label">OUTLOOK</span><h2>Vessel reports pending</h2><span class="badge unknown">Not connected</span><p>Outlook screen access through VMware Horizon has been verified. Automated noon, port and working report collection and reconciliation are still pending.</p></article><article class="connection-card"><span class="connection-label">POSITION</span><h2>Positions pending</h2><span class="badge unknown">Awaiting verified positions</span><p>Port calls are scheduled destinations, not current vessel positions. The map will use position reports with a verified source and timestamp.</p></article></div>`;}
function render(){document.querySelector('#main').innerHTML=page==='fleet'?fleet():page==='review'?review():page==='brief'?briefing():connections();document.querySelector('#breadcrumb').textContent=navs.find(n=>n[0]===page)[1];document.querySelectorAll('.nav-item').forEach(b=>{b.classList.toggle('active',b.dataset.page===page);b.setAttribute('aria-current',b.dataset.page===page?'page':'false');});document.querySelector('.sidebar').classList.remove('open');document.querySelector('#menu').setAttribute('aria-expanded','false');if(page==='fleet'){renderRows();document.querySelector('#sort').value=sort;}}
function navigate(p){if(!navs.some(n=>n[0]===p))return;close();page=p;location.hash=p;render();window.scrollTo(0,0);}
function open(id){selected=rows.find(v=>v.id===id);if(!selected)return;lastFocus=document.activeElement;const v=selected;document.querySelector('#drawer-root').innerHTML=`<div class="drawer-backdrop" id="backdrop"></div><section class="drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title"><div class="drawer-top"><span class="eyebrow">DATALOY VOYAGE</span><button class="icon-button" id="close" aria-label="Close voyage details">${icon('close')}</button></div><div class="drawer-title"><div><h2 id="drawer-title">${esc(v.name)}</h2><p>Voyage ${esc(v.voyage)} · Ref ${esc(v.reference)} <span class="opr">OPR</span></p></div></div><div class="drawer-content">${badge(v)}<div class="detail-grid"><div><small>Registered start · UTC</small><strong>${stamp(v.start)}</strong><span>Dataloy registered schedule</span></div><div><small>Registered end · UTC</small><strong>${stamp(v.end)}</strong><span>Not a verified completion time</span></div><div><small>Vessel position</small><strong>Not verified</strong><span>No verified position feed</span></div><div><small>Report reconciliation</small><strong>Not performed</strong><span>Outlook collection not connected</span></div></div><h3 class="ports-heading">Registered port rotation</h3><ol class="port-sequence">${v.ports.map(p=>`<li><span>${esc(p.name)}</span><small>Sequence ${esc(p.sequence??'Not verified')}</small></li>`).join('')}</ol><p class="subtle-note">This rotation is a registered schedule, not a record of completed calls or the current vessel position. Vessel ETA and planned-versus-actual reconciliation are pending.</p></div><div class="drawer-footer"><span>Snapshot · ${stamp(asOf)} UTC</span></div></section>`;document.body.classList.add('drawer-open');document.querySelector('.shell').inert=true;document.querySelector('.sidebar').inert=true;document.querySelector('#close').focus();}
function close(){document.querySelector('#drawer-root').innerHTML='';document.body.classList.remove('drawer-open');document.querySelector('.shell').inert=false;document.querySelector('.sidebar').inert=false;selected=null;lastFocus?.focus();}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
document.addEventListener('click',e=>{if(e.target.id==='backdrop')return close();const b=e.target.closest('button');if(!b)return;if(b.dataset.page)return navigate(b.dataset.page);if(b.dataset.voyage)return open(b.dataset.voyage);if(b.dataset.filter){filter=b.dataset.filter;renderRows();return;}if(b.id==='menu'){const shown=document.querySelector('.sidebar').classList.toggle('open');b.setAttribute('aria-expanded',String(shown));}if(b.id==='close')close();if(b.id==='clear'){search='';filter='all';document.querySelector('#fleet-search').value='';renderRows();}if(b.id==='export')download('dataloy-operational-snapshot.csv',snapshotCsv(current(),asOf),'text/csv;charset=utf-8');if(b.id==='brief-download')download('dataloy-voyage-brief.txt',`Dataloy snapshot ${asOf}\n${vesselCount} vessels / ${rows.length} voyages / ${past.length} end dates passed\nAutomatic refresh and Outlook reconciliation not connected\n\n`+rows.map(v=>`${v.name} | ${v.voyage} | ${portNames(v)} | Registered end ${v.end} | ${labels[state(v)]}`).join('\n'),'text/plain;charset=utf-8');});
document.addEventListener('input',e=>{if(e.target.id==='fleet-search'){search=e.target.value;renderRows();}});
document.addEventListener('change',e=>{if(e.target.id==='sort'){sort=e.target.value;renderRows();}});
document.addEventListener('keydown',e=>{if(selected&&e.key==='Escape')close();if(selected&&e.key==='Tab'){e.preventDefault();document.querySelector('#close').focus();}});
window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(p==='main'){document.querySelector('#main').focus();return;}if(navs.some(n=>n[0]===p)&&page!==p){close();page=p;render();}});
render();
