import './style.css';
import {vessels,AS_OF,ageHours,etaDelta,filterVessels,coordinates,coordinatesDM,csvExport,fleetCounts,locode,SEVERITY,STATUS} from './data.js';
import {createFleetMap} from './map.js';

/* Icons are kept for controls whose only affordance is the glyph (nav rail when
   collapsed, close, chevron, search, menu). Labels carry no decorative icons. */
const paths={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',check:'m5 12 4 4L19 6',chevron:'m9 5 7 7-7 7',arrow:'M5 12h14m-5-5 5 5-5 5',search:'M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16m6-2 6 6',doc:'M6 2h8l4 4v16H6z M14 2v5h5 M9 12h6m-6 4h6',link:'m10 14 4-4m-6 7-2 2a4 4 0 0 1-6-6l5-5m11-1 2-2a4 4 0 0 1 6 6l-5 5',close:'m6 6 12 12M6 18 18 6',menu:'M4 6h16M4 12h16M4 18h16'};
const icon=(name,size=16)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]}"/></svg>`;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

let page='fleet',search='',status='all',issueOnly=false,mapView=true,sort='attention',fleetMap=null,selected=null,drawerTab='overview',lastFocus=null;
let ack={};try{ack=JSON.parse(localStorage.getItem('fleet-demo-ack-v1')||'{}');}catch{}

/* ---- notation ------------------------------------------------------------
   Deterministic UTC stamps in the form a deck officer writes them: 14 Sep 08:00Z.
   No locale surprises, no ship's-time conversion (we do not hold the offsets). */
const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const stamp=value=>{if(!value)return null;const d=new Date(value);return `${String(d.getUTCDate()).padStart(2,'0')} ${MONTHS[d.getUTCMonth()]} ${String(d.getUTCHours()).padStart(2,'0')}:${String(d.getUTCMinutes()).padStart(2,'0')}Z`;};
const stampLong=value=>value?stamp(value).replace('Z',' UTC'):'Not available';
const hoursText=h=>h>=24?`${Math.floor(h/24)}d ${Math.round(h%24)}h`:`${Number.isInteger(h)?h:h.toFixed(1)}h`;
const age=v=>{const a=ageHours(v);return a===null?'no report received':`reported ${Number.isInteger(a)?a:a.toFixed(1)}h ago`;};
const isStale=v=>{const a=ageHours(v);return a!==null&&a>30;};
const toGo=v=>{if(!v.eta)return null;const h=(Date.parse(v.eta)-Date.parse(AS_OF))/3600000;return h>0?hoursText(h):null;};
const deltaText=v=>{const d=etaDelta(v);return d===null?'no plan comparison':d===0?'on plan':`${d>0?'+':'−'}${Math.abs(d)}h vs plan`;};
const sev=v=>`<span class="sev sev-${v.severity}"><i aria-hidden="true">${SEVERITY[v.severity].mark}</i>${SEVERITY[v.severity].label}</span>`;
const counts=()=>fleetCounts(vessels);
const navs=[['fleet','grid','Fleet overview'],['review','check','Review queue'],['brief','doc','Daily brief'],['connections','link','Data connections']];

/* ---- shell --------------------------------------------------------------- */
const c0=counts();
document.querySelector('#app').innerHTML=`<a class="skip" href="#main">Skip to main content</a><aside class="sidebar"><a class="brand" href="#fleet"><b>FLEET</b><span>OPERATIONS</span></a><nav aria-label="Sections">${navs.map(([id,i,label])=>`<button class="nav-item" data-page="${id}">${icon(i,17)}<span>${label}</span>${id==='review'?`<span class="nav-count">${c0.review+c0.unknown}</span>`:''}</button>`).join('')}</nav><div class="rail-foot"><button class="sources" data-page="connections"><span class="label">Data sources</span><span class="src"><b>Outlook</b><i class="src-state off">not connected</i></span><span class="src"><b>Dataloy</b><i class="src-state off">no credentials</i></span><span class="src snap"><b>Snapshot</b><i>${stamp(AS_OF)}</i></span></button><button class="user" data-page="connections"><span class="avatar">FO</span><span>Operations team<small>Review workspace</small></span></button></div></aside><div class="shell"><header class="topbar"><button class="icon-button mobile-menu" aria-label="Open menu">${icon('menu',18)}</button><span class="clock">${stamp(AS_OF)}</span><span class="tz">all times UTC</span><span class="spacer"></span><span class="demo-pill">Demo workspace &middot; synthetic data</span><span class="avatar small">FO</span></header><main id="main" tabindex="-1"></main><footer class="footer"><span>VMwareconnect &middot; Fleet Operations</span><span>Synthetic review data &middot; not live operations</span></footer></div><div id="drawer-root"></div><div id="toast" role="status" aria-live="polite"></div>`;

/* The page title is printed once, here. The rail marks the section, the document
   title carries it for the browser; no eyebrow and no breadcrumb repeat it. */
function header(title,description,actions=''){return `<div class="masthead"><div><h1>${title}</h1><p>${description}</p></div>${actions?`<div class="masthead-actions">${actions}</div>`:''}</div>`;}
function provenance(){const c=counts();return `<div class="provenance"><span class="tag">Synthetic demo data</span><span>${c.total} vessels &middot; snapshot ${stampLong(AS_OF)}</span><span>Positions are last reported, not live AIS</span><span>Ship's clocks not applied</span><button data-page="connections">Live data readiness ${icon('arrow',13)}</button></div>`;}
function currentList(){const l=filterVessels(vessels,{search,status,issueOnly});return l.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):SEVERITY[a.severity].rank-SEVERITY[b.severity].rank||a.name.localeCompare(b.name));}

/* ---- fleet page ---------------------------------------------------------- */
function statusBoard(){const c=counts();const board=[...vessels].sort((a,b)=>SEVERITY[a.severity].rank-SEVERITY[b.severity].rank||a.name.localeCompare(b.name));
 /* filters and their counts both come from the data, so neither can go stale */
 const chips=STATUS.map(({code,label})=>[code,label,code==='all'?c.total:c[code]]);
 return `<section class="board" aria-label="Fleet status"><div class="board-row"><div class="board-read"><span class="label">Fleet status</span><p><strong>${c.review}</strong> of ${c.total} vessels need review<i>&middot;</i><strong>${c.unknown}</strong> on hold, finding withheld<i>&middot;</i>${c.ok} aligned</p></div><div class="board-tiles">${board.map((v,i)=>`${i&&v.severity==='ok'&&board[i-1].severity!=='ok'?'<span class="tile-gap" aria-hidden="true"></span>':''}<button class="tile sev-${v.severity}" data-vessel="${v.id}" title="${esc(v.name)} — ${SEVERITY[v.severity].label}"><span>${v.short}</span></button>`).join('')}</div></div><div class="board-filters">${chips.map(([code,label,n])=>`<button class="chip${status===code?' active':''}" data-status="${code}">${label}<b>${n}</b></button>`).join('')}<button class="chip toggle" id="issue-filter" aria-pressed="${issueOnly}">Findings only</button></div></section>`;}

/* One vessel, one scannable unit: identity + verdict / state + freshness /
   voyage leg + cargo / does the plan still hold. */
function vesselRecord(v){
 const stale=isStale(v);
 const a=ageHours(v);
 /* "reported" is dropped at narrow widths so the record never wraps to three lines */
 const reported=a===null?`<span class="unreported">no report received</span>`:`<span class="${stale?'stale':''}"><i class="rep-word">reported </i>${Number.isInteger(a)?a:a.toFixed(1)}h ago</span>`;
 let line2;
 if(v.statusCode==='alongside'&&v.progress) line2=`<span class="load" aria-hidden="true"><i style="width:${v.progress}%"></i></span><b class="num">${v.progress}%</b> ${v.activity==='Loading'?'loaded':'discharged'} <i>&middot;</i> ${reported}`;
 else if(v.statusCode==='check') line2=`${reported} <i>&middot;</i> coverage unverified`;
 else if(v.speed!==null) line2=`<b class="num">${v.speed.toFixed(1)} kn</b> <i>&middot;</i> <b class="num">${String(v.course).padStart(3,'0')}&deg;T</b> <i>&middot;</i> ${reported}`;
 else line2=reported;
 const go=toGo(v);
 const etaLine=v.eta?`<b class="num">${Date.parse(v.eta)<Date.parse(AS_OF)?'Arrived':'ETA'} ${stamp(v.eta)}</b>`:`<b class="none">ETA not reported</b>`;
 const planLine=v.eta?`${go?`${go} to go <i>&middot;</i> `:''}<span class="${Math.abs(etaDelta(v))>=12?'off-plan':''}">${deltaText(v)}</span>`:`Plan <b class="num">${stamp(v.planEta)}</b> <i>&middot;</i> finding withheld`;
 return `<li><button class="record sev-${v.severity}" data-vessel="${v.id}">
  <span class="r-id"><span class="r-name"><b class="code">${v.short}</b><strong>${v.name}</strong>${sev(v)}</span><span class="r-sub">${v.type} <i>&middot;</i> ${v.voyage}<em>${v.issue?esc(v.issue):''}</em></span></span>
  <span class="r-state"><span class="r-top">${v.status} <i>&mdash;</i> ${v.activity}</span><span class="r-sub">${line2}</span></span>
  <span class="r-leg"><span class="r-top">${v.from} <i class="lead">&#9656;</i> ${v.to}</span><span class="r-sub"><b class="num">${locode(v.from)} ▸ ${locode(v.to)}</b> <i class="cargo">&middot;</i> <span class="cargo">${v.cargo==='Ballast'?'in ballast':v.cargo==='Not available'?'cargo not reported':`${esc(v.quantity)} ${v.cargo.toLowerCase()}`}</span></span></span>
  <span class="r-plan"><span class="r-top">${etaLine}</span><span class="r-sub">${planLine}</span></span>
  <span class="r-go" aria-hidden="true">${icon('chevron',14)}</span></button></li>`;}

function renderRows(){const list=currentList();const c=counts();
 document.querySelector('#vessel-list').innerHTML=list.length?list.map(vesselRecord).join(''):`<li class="empty-state"><strong>No vessels match</strong><p>Try another vessel name, voyage number, port or LOCODE.</p><button class="button" id="clear-filters">Clear filters</button></li>`;
 document.querySelector('#result-count').textContent=list.length;
 document.querySelector('#list-foot').textContent=`${list.length} of ${c.total} vessels · sorted by ${sort==='name'?'vessel name':'review priority'}`;
 const mc=document.querySelector('#map-count');if(mc)mc.textContent=`${list.filter(v=>v.position).length} of ${list.length} plotted`;
 document.querySelector('#issue-filter').setAttribute('aria-pressed',String(issueOnly));
 document.querySelector('#issue-filter').classList.toggle('active',issueOnly);
 document.querySelectorAll('[data-status]').forEach(b=>b.classList.toggle('active',b.dataset.status===status));
 fleetMap?.update(list);}

function diffPanel(){const list=vessels.filter(v=>v.discrepancy).sort((a,b)=>SEVERITY[a.severity].rank-SEVERITY[b.severity].rank);
 return `<aside class="diff-panel"><div class="panel-head"><h2>Reported vs Dataloy</h2><span class="label">${list.length} open</span></div><p class="panel-note">The two values behind each finding, side by side.</p><ul class="diff-list">${list.map(v=>`<li class="sev-${v.severity}"><button data-vessel="${v.id}"><span class="d-head"><b class="code">${v.short}</b><strong>${v.name}</strong>${sev(v)}</span><span class="d-field">${esc(v.discrepancy.field)}</span><span class="d-row"><i>Vessel report</i><b class="num">${esc(v.discrepancy.reported)}</b></span><span class="d-row"><i>Dataloy</i><b class="num">${esc(v.discrepancy.dataloy)}</b></span><span class="d-delta">${esc(v.discrepancy.delta)}</span></button></li>`).join('')}</ul><button class="text-button" data-page="review">Open the review queue ${icon('arrow',14)}</button></aside>`;}

function fleetPage(){return header('Fleet overview','Where every vessel reported last, and where her own report disagrees with Dataloy.',`<button class="button" id="export">Export fleet (CSV)</button><button class="button primary" data-page="brief">Daily brief</button>`)+provenance()+statusBoard()+`
<section class="list-panel"><div class="list-head"><h2>Vessels <span id="result-count">${counts().total}</span></h2><div class="list-controls"><label class="search">${icon('search',15)}<input id="fleet-search" placeholder="Vessel, voyage, port or LOCODE" aria-label="Search vessel, voyage, port or LOCODE" value="${esc(search)}"></label><label class="sort-label">Sort<select id="sort" aria-label="Sort vessels"><option value="attention">Review first</option><option value="name">Vessel name</option></select></label></div></div>
<div class="list-cols" aria-hidden="true"><span>Vessel &middot; finding</span><span>State &middot; last report</span><span>Voyage leg &middot; cargo</span><span>ETA &middot; against plan</span><span></span></div>
<ul class="records" id="vessel-list"></ul><div class="list-foot"><span id="list-foot"></span><span>Synthetic snapshot &middot; ${stamp(AS_OF)}</span></div></section>
<section class="support" id="support">${diffPanel()}<div class="map-panel"><div class="panel-head"><h2>Last reported positions</h2><span class="label" id="map-count"></span><span class="spacer"></span><button class="text-button" id="reset-map">Fit fleet</button><button class="text-button" id="toggle-map">Hide map</button></div><div id="fleet-map" aria-label="Map of last reported vessel positions across the Indian Ocean"></div><div class="map-foot"><span class="map-legend"><i class="key sev-critical"></i>Priority<i class="key sev-warn"></i>Review<i class="key sev-unknown"></i>On hold<i class="key sev-ok"></i>Aligned</span><span id="map-status">Pins carry each vessel's code. Hover a vessel above to locate her.</span></div></div></section>`;}

/* ---- review queue -------------------------------------------------------- */
function reviewPage(){const list=vessels.filter(v=>v.severity!=='ok').sort((a,b)=>SEVERITY[a.severity].rank-SEVERITY[b.severity].rank);const done=Object.keys(ack).filter(k=>ack[k]).length;
 return header('Review queue','Work the differences between vessel reports and Dataloy, starting from the evidence.')+provenance()+`<div class="tally"><span><b class="num">${list.filter(v=>v.severity!=='unknown').length}</b>Operational</span><span><b class="num">${list.filter(v=>v.severity==='unknown').length}</b>Data quality</span><span><b class="num">${done}</b>Acknowledged</span></div><div class="review-grid">${list.map(v=>`<article class="review-card sev-${v.severity}"><div class="review-top">${sev(v)}<span class="label">${v.severity==='unknown'?'Data quality':'Operational'}</span></div><h2>${esc(v.issue)}</h2><button class="vessel-link" data-vessel="${v.id}"><b class="code">${v.short}</b>${v.name} ${icon('arrow',14)}</button><p>${esc(v.reason)}</p><div class="compare"><p class="compare-field">${esc(v.discrepancy.field)}</p><dl><div><dt>Vessel report</dt><dd class="num">${esc(v.discrepancy.reported)}</dd></div><div><dt>Dataloy</dt><dd class="num">${esc(v.discrepancy.dataloy)}</dd></div></dl></div><div class="review-actions"><button class="button" data-vessel="${v.id}">View evidence</button><button class="button ${ack[v.id]?'acknowledged':''}" data-ack="${v.id}">${ack[v.id]?'Acknowledged &middot; undo':'Acknowledge'}</button></div></article>`).join('')}</div><p class="subtle-note">Acknowledgements are stored in this browser only. Nothing is resolved in Dataloy and no operational record is changed.</p>`;}

/* ---- daily brief --------------------------------------------------------- */
function briefText(){const c=counts();return `Fleet Operations — DEMO DAILY BRIEF\n${stampLong(AS_OF)}\nSynthetic data. Not live operational information.\nPositions are last reported, not live AIS. Ship's clocks not applied.\n\n${c.total} vessels: ${c.sea} at sea / ${c.alongside} alongside / ${c.anchor} at anchor / ${c.check} unconfirmed\n${c.review} operational review items · ${c.unknown} coverage check\n\n${vessels.map(v=>`${v.name.padEnd(16)} | ${v.status.padEnd(11)} | ${locode(v.from)}>${locode(v.to)} | ETA ${v.eta?stamp(v.eta):'not reported'} | ${v.issue||'Aligned'}`).join('\n')}`;}
function briefPage(){const c=counts();const first=vessels.filter(v=>v.severity==='critical'||v.severity==='warn').sort((a,b)=>SEVERITY[a.severity].rank-SEVERITY[b.severity].rank);
 return header('Daily brief','The day’s fleet picture and what to check first.',`<button class="button primary" id="download-brief">Download brief (TXT)</button>`)+provenance()+`<article class="brief"><div class="brief-top"><span>Fleet Operations · daily brief 001</span><span class="num">${stampLong(AS_OF)}</span></div><h2>${c.review} of ${c.total} vessels need operational review.</h2><p class="brief-lead">For ${c.unknown} vessel the missing-report finding is withheld until collection coverage is verified. ${c.ok} vessels agree with Dataloy within tolerance.</p><h3><span class="num">01</span> Check these first</h3><ol class="brief-items">${first.map(v=>`<li class="sev-${v.severity}"><button data-vessel="${v.id}"><span class="b-head"><b class="code">${v.short}</b><strong>${v.name}</strong><em>${esc(v.issue)}</em>${sev(v)}</span><p>${esc(v.reason)}</p></button></li>`).join('')}</ol><h3><span class="num">02</span> Vessel summary</h3><table class="brief-table"><thead><tr><th>Vessel</th><th>State</th><th>Leg</th><th>ETA</th><th>Comparison</th></tr></thead><tbody>${vessels.map(v=>`<tr class="sev-${v.severity}"><td><button data-vessel="${v.id}"><b class="code">${v.short}</b>${v.name}</button></td><td>${v.status}</td><td class="num">${locode(v.from)} ▸ ${locode(v.to)}</td><td class="num">${v.eta?stamp(v.eta):'not reported'}</td><td>${sev(v)}</td></tr>`).join('')}</tbody></table><p class="brief-note">Built from a deterministic template over the synthetic snapshot at ${stampLong(AS_OF)}. For screen review before Outlook and Dataloy are connected.</p></article>`;}

/* ---- data connections ---------------------------------------------------- */
function connectionsPage(){const c=counts();const task=(done,text)=>`<li class="${done?'done':''}"><i aria-hidden="true">${done?'✓':''}</i>${text}<span class="sr-only">${done?' (done)':' (outstanding)'}</span></li>`;
 return header('Data connections','Connection status and what is still required before live data.')+provenance()+`<div class="connection-grid"><article class="connection-card"><div class="conn-top"><span class="label">Source 01</span>${sev({severity:'warn'})}</div><h2>VMware · Outlook</h2><p class="conn-state">Automated collection not connected</p><p>Screen access to the Horizon desktop is confirmed. Automated report collection and cloud delivery still need separate verification.</p><ul class="tasks">${task(true,'Horizon screen access confirmed')}${task(false,'Verify Graph / COM path')}${task(false,'Verify HTTPS batch upload')}</ul></article><article class="connection-card"><div class="conn-top"><span class="label">Source 02</span>${sev({severity:'unknown'})}</div><h2>Dataloy VMS</h2><p class="conn-state">Awaiting credentials</p><p>Operational voyages, port call plans and recorded actuals will be connected read-only.</p><ul class="tasks">${task(false,'Confirm API base URL')}${task(false,'Set server runtime secrets')}${task(false,'Verify field, time and event semantics')}</ul></article><article class="connection-card"><div class="conn-top"><span class="label">Workspace</span>${sev({severity:'ok'})}</div><h2>Review dashboard</h2><p class="conn-state">Demo mode</p><p>A static site for reviewing the screens. Live mode adds an authenticated API, a worker and PostgreSQL.</p><ul class="tasks">${task(true,`${c.total} synthetic vessels`)}${task(true,'Map, comparison and brief')}${task(false,'Live data API and sign-in')}</ul></article></div><section class="flow-panel"><h2>How the data will connect</h2><ol class="flow"><li><span class="num">1</span>Collect reports inside the VM</li><li><span class="num">2</span>Authenticated HTTPS upload</li><li><span class="num">3</span>Normalise and compare with Dataloy</li><li><span class="num">4</span>Fleet dashboard</li></ol><p class="subtle-note">This review site accepts no API keys. Keys are set as encrypted DigitalOcean runtime secrets on the live backend.</p></section>`;}

/* ---- render -------------------------------------------------------------- */
function render(){fleetMap?.destroy();fleetMap=null;
 document.querySelector('#main').innerHTML=page==='fleet'?fleetPage():page==='review'?reviewPage():page==='brief'?briefPage():connectionsPage();
 const label=navs.find(n=>n[0]===page)[2];document.title=`${label} · Fleet Operations`;
 document.querySelectorAll('.nav-item').forEach(b=>{b.classList.toggle('active',b.dataset.page===page);b.setAttribute('aria-current',b.dataset.page===page?'page':'false');});
 if(page==='fleet'){renderRows();try{fleetMap=createFleetMap('fleet-map',currentList(),openVessel);}catch{document.querySelector('#map-status').textContent='This environment cannot render the map. The vessel list above carries every reported position.';}
  document.querySelector('#sort').value=sort;updateView();
  const list=document.querySelector('#vessel-list');
  list.addEventListener('mouseover',e=>{const r=e.target.closest('[data-vessel]');if(r)fleetMap?.highlight(r.dataset.vessel);});
  list.addEventListener('mouseleave',()=>fleetMap?.highlight(null));
  list.addEventListener('focusin',e=>{const r=e.target.closest('[data-vessel]');if(r)fleetMap?.highlight(r.dataset.vessel);});}
 document.querySelector('.sidebar').classList.remove('open');}
function navigate(p){if(!navs.some(n=>n[0]===p))p='fleet';page=p;location.hash=p;render();}
function updateView(){const panel=document.querySelector('.map-panel');panel.classList.toggle('collapsed',!mapView);document.querySelector('#toggle-map').textContent=mapView?'Hide map':'Show map';if(mapView)requestAnimationFrame(()=>fleetMap?.map.resize());}

/* ---- vessel drawer ------------------------------------------------------- */
function overview(v){const go=toGo(v);
 return `<p class="drawer-reason">${esc(v.reason)}</p><div class="leg-strip"><div><span class="label">From</span><strong>${v.from}</strong><b class="num">${locode(v.from)}</b></div><i aria-hidden="true">&#9656;</i><div><span class="label">${v.statusCode==='alongside'?'Current port':'Next port'}</span><strong>${v.to}</strong><b class="num">${locode(v.to)}</b></div></div><dl class="detail-grid"><div><dt>Last reported position</dt><dd class="num">${coordinatesDM(v.position)}</dd><small>${v.reportedAt?`${stampLong(v.reportedAt)} · ${age(v)}`:'No report time recorded'}</small></div><div><dt>Speed &amp; course</dt><dd class="num">${v.speed===null?'Not available':`${v.speed.toFixed(1)} kn · ${String(v.course).padStart(3,'0')}°T`}</dd><small>Observed at report time</small></div><div><dt>${v.eta&&Date.parse(v.eta)<Date.parse(AS_OF)?'Reported arrival':'Vessel ETA'}</dt><dd class="num">${stampLong(v.eta)}</dd><small>${go?`${go} to go · `:''}${deltaText(v)}</small></div><div><dt>Dataloy planned ETA</dt><dd class="num">${stampLong(v.planEta)}</dd><small>Synthetic plan snapshot</small></div><div><dt>Cargo</dt><dd>${esc(v.cargo)}</dd><small>${esc(v.quantity)}</small></div><div><dt>VLSFO ROB</dt><dd class="num">${v.rob===null?'Not available':`${v.rob.toFixed(1)} MT`}</dd><small>Not compared against ROB from another time</small></div></dl>${v.progress?`<section class="cargo-progress"><div><h3>${v.activity}</h3><strong class="num">${v.progress}%</strong></div><div class="progress-bar"><i style="width:${v.progress}%"></i></div><p>Validated cumulative quantity over planned total, from the synthetic working report.</p></section>`:''}<button class="evidence-callout" data-drawer-tab="evidence"><span><strong>See the evidence behind this</strong><small>Open the synthetic report and the Dataloy comparison.</small></span>${icon('arrow',18)}</button>`;}
function timeline(v){return `<p class="timeline-note">Vessel report, plan and recorded actual are kept apart. A missing actual is never scored as aligned.</p><div class="comparison-scroll"><table class="comparison"><thead><tr><th>Item</th><th>Vessel report</th><th>Dataloy plan</th><th>Recorded actual</th></tr></thead><tbody><tr><th>Next port ETA</th><td class="num">${stampLong(v.eta)}</td><td class="num">${stampLong(v.planEta)}</td><td>Not applicable</td></tr><tr><th>Position</th><td class="num">${coordinates(v.position)}</td><td>Not applicable</td><td>No comparable data</td></tr>${v.id==='v2'?'<tr class="highlight-row"><th>All Fast</th><td class="num">13 Sep 06:10 UTC</td><td class="num">13 Sep 05:00 UTC</td><td>Not recorded</td></tr><tr><th>Arrival</th><td class="num">13 Sep 04:00 UTC</td><td class="num">13 Sep 04:00 UTC</td><td class="num">13 Sep 04:00 UTC</td></tr>':''}</tbody></table></div>${v.id==='v2'?'<p class="timeline-note">Arrival and All Fast are separate events. An arrival actual on its own does not settle the berthing report.</p>':''}`;}
function evidence(v){return `<p class="label evidence-label">Synthetic report · sample source text</p><pre class="report-preview">${esc(`VESSEL: ${v.name}\nVOYAGE: ${v.voyage}\nREPORT TYPE: ${v.statusCode==='alongside'?'WORKING / PORT REPORT':'NOON REPORT'}\nREPORT TIME: ${stampLong(v.reportedAt)}\nPOSITION: ${coordinatesDM(v.position)}\nCOURSE: ${String(v.course).padStart(3,'0')} DEG TRUE\nSPEED: ${v.speed??'UNKNOWN'} KN\nNEXT PORT: ${v.to} (${locode(v.to)})\nETA: ${stampLong(v.eta)}\nVLSFO ROB: ${v.rob??'UNKNOWN'} MT${v.id==='v2'?'\nALL FAST: 13 SEP 2026 06:10 UTC':''}\n\nDEMO DATA ONLY — NOT AN ACTUAL EMAIL.`)}</pre><dl class="evidence-metadata"><div><dt>Source</dt><dd>Synthetic report for screen review</dd></div><div><dt>Source access</dt><dd>Outlook not connected</dd></div><div><dt>Position use</dt><dd>${v.position?'Example reported observation':'Unverified · kept off the map'}</dd></div></dl><p class="subtle-note">Once live data is connected, the source locator and per-field extraction evidence are served within the caller’s permissions.</p>`;}
function openVessel(id){selected=vessels.find(v=>v.id===id);if(!selected)return;drawerTab='overview';lastFocus=document.activeElement;fleetMap?.select(selected);renderDrawer();document.querySelector('#close-drawer').focus();}
function renderDrawer(){const v=selected;document.querySelector('#drawer-root').innerHTML=`<div class="drawer-backdrop" id="drawer-backdrop"></div><section class="drawer sev-${v.severity}" role="dialog" aria-modal="true" aria-labelledby="drawer-title"><div class="drawer-title"><b class="code">${v.short}</b><div><h2 id="drawer-title">${v.name}</h2><p>${v.type} <i>&middot;</i> voyage ${v.voyage} <i>&middot;</i> ${v.status} &mdash; ${v.activity}</p></div>${sev(v)}<button class="icon-button" id="close-drawer" aria-label="Close vessel detail">${icon('close',18)}</button></div><div class="drawer-tabs" role="tablist" aria-label="Vessel detail tabs">${[['overview','Situation'],['timeline','Dataloy comparison'],['evidence','Evidence']].map(([key,label])=>`<button role="tab" aria-selected="${drawerTab===key}" class="${drawerTab===key?'active':''}" data-drawer-tab="${key}">${label}</button>`).join('')}</div><div class="drawer-content">${drawerTab==='overview'?overview(v):drawerTab==='timeline'?timeline(v):evidence(v)}</div><div class="drawer-footer"><span>Synthetic data · ${stampLong(AS_OF)}</span>${v.severity!=='ok'?`<button class="button primary" data-ack="${v.id}">${ack[v.id]?'Undo acknowledgement':'Acknowledge'}</button>`:''}</div></section>`;document.body.classList.add('drawer-open');}
function closeDrawer(){document.querySelector('#drawer-root').innerHTML='';document.body.classList.remove('drawer-open');selected=null;lastFocus?.focus();}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('visible'),3000);}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('Downloaded a synthetic data file.');}

document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(e.target.id==='drawer-backdrop')return closeDrawer();if(!b)return;
 if(b.dataset.page)return navigate(b.dataset.page);
 if(b.dataset.vessel)return openVessel(b.dataset.vessel);
 if(b.dataset.drawerTab){drawerTab=b.dataset.drawerTab;renderDrawer();document.querySelector(`[data-drawer-tab="${drawerTab}"]`)?.focus();return;}
 if(b.dataset.ack){ack[b.dataset.ack]=!ack[b.dataset.ack];try{localStorage.setItem('fleet-demo-ack-v1',JSON.stringify(ack));toast('Updated the review state in this browser.');}catch{toast('Browser storage is unavailable, so this applies to the current session only.');}if(selected)renderDrawer();else render();return;}
 if(b.dataset.status){status=b.dataset.status;renderRows();return;}
 if(b.classList.contains('mobile-menu'))document.querySelector('.sidebar').classList.toggle('open');
 if(b.id==='close-drawer')closeDrawer();
 if(b.id==='export')download('fleet-demo-2026-09-14.csv',csvExport(currentList()),'text/csv;charset=utf-8');
 if(b.id==='download-brief')download('fleet-demo-brief-2026-09-14.txt',briefText(),'text/plain;charset=utf-8');
 if(b.id==='reset-map')fleetMap?.reset();
 if(b.id==='toggle-map'){mapView=!mapView;updateView();}
 if(b.id==='issue-filter'){issueOnly=!issueOnly;renderRows();}
 if(b.id==='clear-filters'){search='';status='all';issueOnly=false;document.querySelector('#fleet-search').value='';renderRows();}});
document.addEventListener('input',e=>{if(e.target.id==='fleet-search'){search=e.target.value;renderRows();}});
document.addEventListener('change',e=>{if(e.target.id==='sort'){sort=e.target.value;renderRows();}});
document.addEventListener('keydown',e=>{if(!selected)return;if(e.key==='Escape')closeDrawer();if(e.key==='Tab'){const focusable=[...document.querySelectorAll('.drawer button')];const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(next!==page){if(selected)closeDrawer();page=navs.some(n=>n[0]===next)?next:'fleet';render();}});
page=navs.some(n=>n[0]===location.hash.slice(1))?location.hash.slice(1):'fleet';render();
